FROM profideo/php55-apache-node

MAINTAINER Alban Duval <aduval@profideo.com>

# update apt
RUN apt-get update

# Install imagemagick
RUN apt-get install -y imagemagick
RUN apt-get install -y librsvg2-2 librsvg2-bin librsvg2-dbg
RUN apt-get install -y libmagickcore5 libmagickcore5-extra libmagickcore5 libmagickcore5-extra
